%% Init sin
SR = 10000; % sample rate
T = 0.04;   % time, seconds

t = 0:1/SR:T-1/SR;
%y = 0.7*sin(2*pi*40*t+0*pi) + ...
%    0.6*sin(2*pi*150*t+0.35*pi) + ...
%    0.3*rand(size(t)) + ...
%    0.25;

% Square wave
y = 0.0*square(2*pi*50*t-0.2*pi) + ...
    0.0*sawtooth(2*pi*100*t-.1*pi, 0) + ...
    0.0*(rand(size(t))-0.5) + ...
    0.5*sin(2*pi*17*t-0.5*pi) + ...
    0.1*sin(2*pi*100*t+0.35*pi).*sin(2*pi*4000*t+0.0*pi) + ...
    0.5;


plot(t,y,'.-');
grid;
%%
% Low pass square window (moving average)
awin = ones(3,1); % low pass moving average
%awin = gausswin(3);
%awin = Num;

awin = awin/sum(abs(awin));

% Invert filter response by substracting from identity filter
% well... more or less ;)
idwin = zeros(size(awin));
idwin(ceil(length(idwin)/2)) = 1;
awin = 0.9*(1*idwin - 0.999*awin);


%awin = awin/sum(abs(awin));
yfilter = filter(awin, 1, y);

plot(t,y,'.-', ...
    'DisplayName','Original', ...
    'LineWidth', 1.0, ...
    'MarkerSize', 8, ...
    'Color', [0.5 0.6 1]);

%hold on

%plot(t,yfilter,'-',...
%    'DisplayName','Filtrada', ...
%    'LineWidth', 1.5, ...
%    'Color', [0.9 0.3 0.2]);
%
hold off

set(gca, ...
    'Color',[0.89 0.94 0.90], ...
    'XTickLabel', [], ...
    'XAxisLocation', 'top', ...
    'YLim', [-0.2 1.2] ... 
    );

legend1 = legend(gca,'show');
set(legend1,...
    'Position',[0.6 0.9 0.37 0.059],...
    'Orientation','horizontal',...
    'EdgeColor',[1 1 1],...
    'Color',[1 1 1]);

l = get(gca, 'XLabel');
set(l, ...
    'String', 'Señal original sin filtrar', ...
    'HorizontalAlignment', 'center', ...
    'Position', [0.0135    1.2279   -1.0000] ...
    );

grid;

%freqz(awin,1);

%% Low pass RC
%alpha = 0.08;
%yfilter = filter([alpha], [1 -1+alpha], y);

%plot(t,y,'.-');
%hold on
%plot(t,yfilter,'-','LineWidth',2);
%hold off

%grid;

